/**
 * @fileoverview gRPC-Web generated client stub for gamehub.proto.manager.service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: collection.service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as collection_service_pb from './collection.service_pb'; // proto import: "collection.service.proto"


export class CollectionClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreate = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.Collection/Create',
    grpcWeb.MethodType.UNARY,
    collection_service_pb.CollectionCreateRequest,
    collection_service_pb.CollectionUpdateResponse,
    (request: collection_service_pb.CollectionCreateRequest) => {
      return request.serializeBinary();
    },
    collection_service_pb.CollectionUpdateResponse.deserializeBinary
  );

  create(
    request: collection_service_pb.CollectionCreateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<collection_service_pb.CollectionUpdateResponse>;

  create(
    request: collection_service_pb.CollectionCreateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void): grpcWeb.ClientReadableStream<collection_service_pb.CollectionUpdateResponse>;

  create(
    request: collection_service_pb.CollectionCreateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.Collection/Create',
        request,
        metadata || {},
        this.methodDescriptorCreate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.Collection/Create',
    request,
    metadata || {},
    this.methodDescriptorCreate);
  }

  methodDescriptorUpdate = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.Collection/Update',
    grpcWeb.MethodType.UNARY,
    collection_service_pb.CollectionUpdateRequest,
    collection_service_pb.CollectionUpdateResponse,
    (request: collection_service_pb.CollectionUpdateRequest) => {
      return request.serializeBinary();
    },
    collection_service_pb.CollectionUpdateResponse.deserializeBinary
  );

  update(
    request: collection_service_pb.CollectionUpdateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<collection_service_pb.CollectionUpdateResponse>;

  update(
    request: collection_service_pb.CollectionUpdateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void): grpcWeb.ClientReadableStream<collection_service_pb.CollectionUpdateResponse>;

  update(
    request: collection_service_pb.CollectionUpdateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.Collection/Update',
        request,
        metadata || {},
        this.methodDescriptorUpdate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.Collection/Update',
    request,
    metadata || {},
    this.methodDescriptorUpdate);
  }

  methodDescriptorUpdateImage = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.Collection/UpdateImage',
    grpcWeb.MethodType.UNARY,
    collection_service_pb.CollectionUpdateImageRequest,
    collection_service_pb.CollectionUpdateResponse,
    (request: collection_service_pb.CollectionUpdateImageRequest) => {
      return request.serializeBinary();
    },
    collection_service_pb.CollectionUpdateResponse.deserializeBinary
  );

  updateImage(
    request: collection_service_pb.CollectionUpdateImageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<collection_service_pb.CollectionUpdateResponse>;

  updateImage(
    request: collection_service_pb.CollectionUpdateImageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void): grpcWeb.ClientReadableStream<collection_service_pb.CollectionUpdateResponse>;

  updateImage(
    request: collection_service_pb.CollectionUpdateImageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.Collection/UpdateImage',
        request,
        metadata || {},
        this.methodDescriptorUpdateImage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.Collection/UpdateImage',
    request,
    metadata || {},
    this.methodDescriptorUpdateImage);
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.Collection/Info',
    grpcWeb.MethodType.UNARY,
    collection_service_pb.CollectionInfoRequest,
    collection_service_pb.CollectionDetailsResponse,
    (request: collection_service_pb.CollectionInfoRequest) => {
      return request.serializeBinary();
    },
    collection_service_pb.CollectionDetailsResponse.deserializeBinary
  );

  info(
    request: collection_service_pb.CollectionInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<collection_service_pb.CollectionDetailsResponse>;

  info(
    request: collection_service_pb.CollectionInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionDetailsResponse) => void): grpcWeb.ClientReadableStream<collection_service_pb.CollectionDetailsResponse>;

  info(
    request: collection_service_pb.CollectionInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.Collection/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.Collection/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.Collection/List',
    grpcWeb.MethodType.UNARY,
    collection_service_pb.CollectionListRequest,
    collection_service_pb.CollectionListResponse,
    (request: collection_service_pb.CollectionListRequest) => {
      return request.serializeBinary();
    },
    collection_service_pb.CollectionListResponse.deserializeBinary
  );

  list(
    request: collection_service_pb.CollectionListRequest,
    metadata?: grpcWeb.Metadata | null): Promise<collection_service_pb.CollectionListResponse>;

  list(
    request: collection_service_pb.CollectionListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionListResponse) => void): grpcWeb.ClientReadableStream<collection_service_pb.CollectionListResponse>;

  list(
    request: collection_service_pb.CollectionListRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: collection_service_pb.CollectionListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.Collection/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.Collection/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

}

