/**
 * @fileoverview gRPC-Web generated client stub for gamehub.proto.manager.service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: game_variant.service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as game_variant_service_pb from './game_variant.service_pb'; // proto import: "game_variant.service.proto"


export class GameVariantClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUpdate = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.GameVariant/Update',
    grpcWeb.MethodType.UNARY,
    game_variant_service_pb.GameVariantUpdateRequest,
    game_variant_service_pb.GameVariantUpdateResponse,
    (request: game_variant_service_pb.GameVariantUpdateRequest) => {
      return request.serializeBinary();
    },
    game_variant_service_pb.GameVariantUpdateResponse.deserializeBinary
  );

  update(
    request: game_variant_service_pb.GameVariantUpdateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<game_variant_service_pb.GameVariantUpdateResponse>;

  update(
    request: game_variant_service_pb.GameVariantUpdateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantUpdateResponse) => void): grpcWeb.ClientReadableStream<game_variant_service_pb.GameVariantUpdateResponse>;

  update(
    request: game_variant_service_pb.GameVariantUpdateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.GameVariant/Update',
        request,
        metadata || {},
        this.methodDescriptorUpdate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.GameVariant/Update',
    request,
    metadata || {},
    this.methodDescriptorUpdate);
  }

  methodDescriptorInfo = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.GameVariant/Info',
    grpcWeb.MethodType.UNARY,
    game_variant_service_pb.GameVariantInfoRequest,
    game_variant_service_pb.GameVariantDetailsResponse,
    (request: game_variant_service_pb.GameVariantInfoRequest) => {
      return request.serializeBinary();
    },
    game_variant_service_pb.GameVariantDetailsResponse.deserializeBinary
  );

  info(
    request: game_variant_service_pb.GameVariantInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<game_variant_service_pb.GameVariantDetailsResponse>;

  info(
    request: game_variant_service_pb.GameVariantInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantDetailsResponse) => void): grpcWeb.ClientReadableStream<game_variant_service_pb.GameVariantDetailsResponse>;

  info(
    request: game_variant_service_pb.GameVariantInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.GameVariant/Info',
        request,
        metadata || {},
        this.methodDescriptorInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.GameVariant/Info',
    request,
    metadata || {},
    this.methodDescriptorInfo);
  }

  methodDescriptorList = new grpcWeb.MethodDescriptor(
    '/gamehub.proto.manager.service.GameVariant/List',
    grpcWeb.MethodType.UNARY,
    game_variant_service_pb.GameVariantListRequest,
    game_variant_service_pb.GameVariantListResponse,
    (request: game_variant_service_pb.GameVariantListRequest) => {
      return request.serializeBinary();
    },
    game_variant_service_pb.GameVariantListResponse.deserializeBinary
  );

  list(
    request: game_variant_service_pb.GameVariantListRequest,
    metadata?: grpcWeb.Metadata | null): Promise<game_variant_service_pb.GameVariantListResponse>;

  list(
    request: game_variant_service_pb.GameVariantListRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantListResponse) => void): grpcWeb.ClientReadableStream<game_variant_service_pb.GameVariantListResponse>;

  list(
    request: game_variant_service_pb.GameVariantListRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: game_variant_service_pb.GameVariantListResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/gamehub.proto.manager.service.GameVariant/List',
        request,
        metadata || {},
        this.methodDescriptorList,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/gamehub.proto.manager.service.GameVariant/List',
    request,
    metadata || {},
    this.methodDescriptorList);
  }

}

